"""Golden packets generated by KMI's published JavaScript preset encoder."""

import hashlib
import unittest
from pathlib import Path

from kboard_protocol import (
    DEFAULT_PROFILE, _decode_7bit, build_settings_request, build_sysex,
    decode_preset_image, full_preset, parse_settings_dump, preset_image_from_dump,
    validate_profile,
)
DUMP_REPLY = (Path(__file__).parent / "fixtures" / "slot0_dump_reply.bin").read_bytes()


class ProtocolTest(unittest.TestCase):
    def test_default_matches_official_encoder(self):
        packet = build_sysex(DEFAULT_PROFILE)
        self.assertEqual(len(packet), 561)
        self.assertEqual(packet[0], 0xF0)
        self.assertEqual(packet[-1], 0xF7)
        self.assertEqual(
            hashlib.sha256(packet).hexdigest(),
            "1d7b77864c46dfda1628c642901fa20ed52a6e712495ccb59e0906816def81ea",
        )

    def test_mpe_extremes_match_official_encoder(self):
        profile = DEFAULT_PROFILE | dict(
            mpe_active=True, mpe_member_channels=15, pressure_cc=-1,
            tilt_cc=74, bend_range_pad=3, bend_range_tilt=12,
            velocity_sensitivity=254, pressure_sensitivity=233,
            tilt_sensitivity=0, velocity_curve="Invert", on_thresh=127,
            pressure_disabled_return=64, tilt_disabled_return=127,
        )
        self.assertEqual(
            hashlib.sha256(build_sysex(profile)).hexdigest(),
            "911fd4ec6b58c0718af3ba309a3c39c05d7c9c7657ccb9904e8a3c9a2b6f3cc5",
        )
        self.assertEqual(full_preset(profile)["Keyboard_Global_Polyphony_Number"], 15)

    def test_rejects_bad_values_before_build(self):
        with self.assertRaises(ValueError):
            validate_profile(DEFAULT_PROFILE | {"mpe_member_channels": 16})
        with self.assertRaises(ValueError):
            validate_profile(DEFAULT_PROFILE | {"mpe_active": True, "tilt_cc": 20})
        with self.assertRaises(ValueError):
            validate_profile(DEFAULT_PROFILE | {"relative_tilt_amount": 101})
        with self.assertRaises(ValueError):
            validate_profile(DEFAULT_PROFILE | {"relative_tilt_range": 25})
        with self.assertRaises(ValueError):
            validate_profile(DEFAULT_PROFILE | {"pressure_glide_range": 25})
        with self.assertRaises(ValueError):
            validate_profile(DEFAULT_PROFILE | {"relative_tilt_deadzone": 13})
        with self.assertRaises(ValueError):
            validate_profile(DEFAULT_PROFILE | {"relative_pad_amount": 65})
        with self.assertRaises(ValueError):
            validate_profile(DEFAULT_PROFILE | {"relative_pad_deadzone": 13})

    def test_relative_tilt_preset_round_trip_and_old_profiles(self):
        profile = DEFAULT_PROFILE | {
            "mpe_active": True, "pressure_cc": -1, "relative_tilt_amount": 25,
            "relative_tilt_range": 8, "pressure_glide_range": 24,
            "relative_tilt_deadzone": 3, "relative_pad_amount": 12,
            "relative_pad_deadzone": 4,
        }
        preset = full_preset(profile)
        self.assertEqual(preset["CV_In_CV_1_Offset"], 48)
        self.assertEqual(preset["CV_In_CV_1_Max"], 0x77)
        self.assertEqual(preset["CV_In_CV_2_Max"], 8)
        self.assertEqual(full_preset(profile)["CV_In_CV_2_Offset"], 3)
        self.assertEqual(full_preset(profile)["CV_In_CV_1_Min"], 52)
        self.assertEqual(full_preset(profile)["CV_In_CV_2_Min"], 4)
        self.assertEqual(full_preset(profile)["CV_In_CV_2_Channel"], 25)
        self.assertEqual(full_preset(profile)["CV_In_CV_2_CC_Number"], 8)
        image = _decode_7bit(build_sysex(profile)[8:-1])[10:480]
        self.assertEqual(decode_preset_image(image), profile)
        # Earlier custom firmware used only a 0..64 width in CV1 Offset.
        from kboard_protocol import MODEL
        legacy_image = bytearray(image)
        legacy_image[1 + list(MODEL).index("CV_In_CV_1_Max")] = 0x7F
        legacy_image[1 + list(MODEL).index("CV_In_CV_2_Max")] = 127
        legacy_image[1 + list(MODEL).index("CV_In_CV_1_Offset")] = 48
        cursor = 1
        for key in MODEL:
            if key == "Preset_Name":
                continue
            if key in ("CV_In_CV_2_Channel", "CV_In_CV_2_CC_Number"):
                legacy_image[cursor] = 0
            cursor += 2 if "Gain" in key and key != "Globals_Gain" else 1
        legacy_profile = decode_preset_image(bytes(legacy_image))
        self.assertEqual(legacy_profile["relative_tilt_amount"], 25)
        self.assertEqual(legacy_profile["relative_tilt_range"], 12)
        self.assertEqual(legacy_profile["pressure_glide_range"], 0)
        legacy = {key: value for key, value in DEFAULT_PROFILE.items()
                  if not key.startswith(("relative_tilt_", "relative_pad_"))}
        self.assertEqual(validate_profile(legacy), DEFAULT_PROFILE)

    def test_wider_glide_receiver_compensates_relative_tilt_range(self):
        profile = DEFAULT_PROFILE | {
            "relative_tilt_amount": 4,
            "relative_tilt_range": 12,
            "pressure_glide_range": 24,
        }
        preset = full_preset(profile)
        self.assertEqual(preset["CV_In_CV_2_Max"], 2)
        image = _decode_7bit(build_sysex(profile)[8:-1])[10:480]
        self.assertEqual(decode_preset_image(image), profile)

    def test_settings_request_matches_native_command(self):
        self.assertEqual(
            build_settings_request(),
            bytes.fromhex("f0 00 01 5f 7a 1a 00 01 00 02 50 02 44 5d 00 10 00 00 00 00 00 00 00 00 f7"),
        )
        with self.assertRaises(ValueError):
            build_settings_request(4)
    def test_decodes_profile_from_preset_image(self):
        packet = build_sysex(DEFAULT_PROFILE)
        image = _decode_7bit(packet[8:-1])[10:480]
        self.assertEqual(decode_preset_image(image), DEFAULT_PROFILE)
    def test_parses_captured_device_dump(self):
        profile = parse_settings_dump(DUMP_REPLY)
        self.assertTrue(profile["mpe_active"])
        self.assertEqual(profile["mpe_member_channels"], 8)
    def test_device_dump_round_trips_through_encoder(self):
        image = preset_image_from_dump(DUMP_REPLY)
        decoded = decode_preset_image(image)
        packet = _decode_7bit(build_sysex(decoded)[8:-1])
        self.assertEqual(decode_preset_image(packet[10:480]), decoded)
    def test_rejects_corrupt_device_dump(self):
        corrupt = bytearray(DUMP_REPLY)
        corrupt[20] ^= 1
        with self.assertRaisesRegex(ValueError, "checksum"):
            parse_settings_dump(bytes(corrupt))
        with self.assertRaisesRegex(ValueError, "not a preset dump"):
            parse_settings_dump(DUMP_REPLY[:-9] + DUMP_REPLY[-1:])
    def test_rejects_short_preset_image(self):
        with self.assertRaisesRegex(ValueError, "470-byte"):
            decode_preset_image(bytes(469))


if __name__ == "__main__":
    unittest.main()
